# This is a basic workflow to help you get started with Actions

name: Auto_Trigger_Action

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cherry_pick_to_release:
    # The type of runner that the job will run on
    runs-on: macos-latest
    if: contains(github.event.pull_request.labels.*.name, 'release_10')

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Cherry Pick Commit
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release_10
          labels: |
            cherry-pick

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
